// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuwjBR5Fg6C7rfqbxRqdKJp-FOGbiy8P0',
    appId: '1:312486257891:web:ad192e382297b84e1a91d6',
    messagingSenderId: '312486257891',
    projectId: 'dolar-app-c6d72',
    authDomain: 'dolar-app-c6d72.firebaseapp.com',
    storageBucket: 'dolar-app-c6d72.appspot.com',
    measurementId: 'G-TD75ST3NVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD17i-0l9nknSB-JIkmzeHpQA4mughWa7I',
    appId: '1:312486257891:android:049a917a56551a1f1a91d6',
    messagingSenderId: '312486257891',
    projectId: 'dolar-app-c6d72',
    storageBucket: 'dolar-app-c6d72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQzmDm31PXVqkySpHpsKrDQ2dwZJeATRg',
    appId: '1:312486257891:ios:eb9d00d9722bc7171a91d6',
    messagingSenderId: '312486257891',
    projectId: 'dolar-app-c6d72',
    storageBucket: 'dolar-app-c6d72.appspot.com',
    androidClientId: '312486257891-q0ieurj9ltk7k0i41jdsr09bfvul27l8.apps.googleusercontent.com',
    iosClientId: '312486257891-2uko15kn3huqat1r98ribogtqjtak2uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.dollarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQzmDm31PXVqkySpHpsKrDQ2dwZJeATRg',
    appId: '1:312486257891:ios:eb9d00d9722bc7171a91d6',
    messagingSenderId: '312486257891',
    projectId: 'dolar-app-c6d72',
    storageBucket: 'dolar-app-c6d72.appspot.com',
    androidClientId: '312486257891-q0ieurj9ltk7k0i41jdsr09bfvul27l8.apps.googleusercontent.com',
    iosClientId: '312486257891-2uko15kn3huqat1r98ribogtqjtak2uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.dollarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuwjBR5Fg6C7rfqbxRqdKJp-FOGbiy8P0',
    appId: '1:312486257891:web:78a4033eeadd5d3e1a91d6',
    messagingSenderId: '312486257891',
    projectId: 'dolar-app-c6d72',
    authDomain: 'dolar-app-c6d72.firebaseapp.com',
    storageBucket: 'dolar-app-c6d72.appspot.com',
    measurementId: 'G-GTD8FLN3GM',
  );
}
