import { StyleSheet } from "react-native";
import { colors } from "../constants";
import { wp, hp } from "../utils/index";

export const globalStyles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: "#fff",
  },
  wrapper_center: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
  },
  container: {
    paddingHorizontal: wp(10),
    flexGrow: 1,
  },
  containerLess: {
    paddingHorizontal: wp(25),
    flexGrow: 1,
    marginTop: hp(10),
  },
  containerPad: {
    paddingHorizontal: wp(30),
  },
  itemContainer: {
    paddingHorizontal: wp(15),
  },
  scroll: {
    paddingVertical: hp(25),
  },
  supermartLogo: {
    marginTop: hp(20),
    marginBottom: hp(10),
    borderWidth: 1,
  },
  colCenter: {
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
  },
  colStart: {
    justifyContent: "center",
    alignItems: "flex-start",
  },
  rowCenter: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  rowBetweenNoCenter: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  rowAround: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  rowStart: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  rowEnd: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    alignSelf: "flex-end",
    marginRight: hp(15),
  },
  undeline: {
    textDecorationStyle: "solid",
    textDecorationLine: "underline",
  },
  authTitle: {
    paddingTop: hp(80),
  },
  footerBtn: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: hp(15),
    paddingHorizontal: wp(15),
  },
  timesIcon: {
    position: "absolute",
    right: wp(15),
    zIndex: 10,
  },
  marginBottom: {
    marginBottom: 100,
  },
  upperContainer: {
    backgroundColor: colors.lightBg,
    minHeight: hp(105),
    borderRadius: hp(20),
    paddingHorizontal: wp(25),
    paddingTop: hp(15),
  },
  upComingContainer: {
    backgroundColor: "#4370D1",
    minHeight: wp(130),
    borderRadius: hp(15),
    marginVertical: hp(15),
    padding: wp(20),
  },
  upComingContainerV2: {
    backgroundColor: "rgba(40, 64, 185, 0.8)",
    height: wp(110),
    borderRadius: hp(20),
    marginVertical: hp(15),
    padding: wp(12),
  },
  homeTiles: {
    backgroundColor: "transparent",
    height: hp(52),
    width: "100%",
    marginRight: hp(0),
    marginTop: hp(10),
    borderRadius: hp(10),
    borderBottomLeftRadius: 0,
    alignItems: "center",
    justifyContent: "space-between",
    padding: hp(5),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#8DB4F5",
    flexDirection: "row",
    paddingHorizontal: wp(20),
  },
  homeTilesOld: {
    backgroundColor: "#4370D1",
    height: wp(100),
    width: wp(150),
    // backgroundColor: '#E6EDFB',
    // height: wp(135),
    // width: wp(157),
    marginRight: hp(10),
    marginVertical: hp(10),
    borderRadius: hp(10),
    alignItems: "center",
    justifyContent: "center",
    padding: hp(15),
    overflow: "hidden",
  },
  summaryCard: {
    backgroundColor: "#4370D1",
    height: wp(100),
    width: wp(160),
    marginHorizontal: hp(10),
    marginVertical: hp(10),
    borderRadius: hp(5),
    alignItems: "flex-start",
    justifyContent: "space-evenly",
    padding: hp(10),
    overflow: "hidden",
  },
  docImg: {
    flex: 1,
    borderRadius: hp(10),
  },
  docImgBox: {
    height: hp(40),
    width: hp(40),
    borderRadius: hp(10),
  },
  width80: {
    width: wp(200),
  },
  separator: {
    backgroundColor: colors.borderColor,
    height: 1,
    marginVertical: hp(5),
  },
  verticalSpacing: {
    marginVertical: hp(10),
  },
  floatingButton: {
    position: "absolute",
    width: hp(60),
    height: hp(60),
    borderRadius: hp(30),
    backgroundColor: "#56AF69",
    bottom: hp(20),
    right: hp(20),
    alignItems: "center",
    justifyContent: "center",
  },
  planCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FAFAFA",
    borderWidth: 0.7,
    borderColor: "#DADADA",
    borderRadius: hp(8),
    padding: hp(10),
    marginVertical: hp(16),
    minHeight: hp(100),
    marginHorizontal: wp(10),
  },
  AccessControlCard: {
    width: "95%",
    height: hp(110),
    borderRadius: hp(10),
    alignSelf: "center",
    marginTop: hp(10),
    backgroundColor: colors.secondaryBg,
    alignItems: "flex-start",
    justifyContent: "center",
    overflow: "hidden",
  },
  AccessControlCardImg: {
    width: hp(110),
    height: hp(110),
  },
  AccessControlCardDetails: {
    marginLeft: hp(10),
    marginTop: hp(10),
    alignSelf: "flex-start",
  },
  shadowWar: {
    shadowColor: "rgba(0, 0, 0, 0.3)",
    shadowOpacity: 0.7,
    elevation: 6,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 0 },
  },
  dayCard: {
    // width: hp(100),
    // height: hp(50),
    width: hp(45),
    padding: hp(5),
    borderRadius: hp(10),
    borderWidth: hp(1),
    marginRight: hp(20),
    marginVertical: hp(15),
    borderColor: colors.blueColor,
    justifyContent: "center",
    alignItems: "center",
  },
  dayCardSkeleton: {
    // width: hp(100),
    height: hp(65),
    width: hp(45),
    padding: hp(5),
    borderRadius: hp(10),
    marginRight: hp(20),
    marginVertical: hp(15),
    borderColor: colors.blueColor,
    justifyContent: "center",
    alignItems: "center",
  },
  dayCardSelected: {
    width: hp(45),
    padding: hp(5),
    borderRadius: hp(10),
    borderWidth: hp(1),
    marginRight: hp(20),
    marginVertical: hp(15),
    borderColor: colors.blueColor,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.blueColor,
  },
  timeCard: {
    width: hp(120),
    // height: hp(50),
    // padding: hp(10),
    paddingVertical: hp(15),
    borderRadius: hp(50),
    borderWidth: hp(1),
    marginRight: hp(15),
    marginTop: hp(15),
    borderColor: colors.blueColor,
    justifyContent: "center",
    alignItems: "center",
  },
  timeCardSkeleton: {
    width: hp(120),
    height: hp(50),
    // padding: hp(10),
    paddingVertical: hp(15),
    borderRadius: hp(50),
    marginRight: hp(15),
    marginTop: hp(15),
    borderColor: colors.blueColor,
    justifyContent: "center",
    alignItems: "center",
  },
  timeCardSelected: {
    width: hp(120),
    // height: hp(50),
    paddingVertical: hp(15),
    borderRadius: hp(50),
    borderWidth: hp(1),
    marginRight: hp(15),
    marginTop: hp(15),
    borderColor: colors.blueColor,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.blueColor,
  },
  timeCardBetween: {
    width: hp(140),
    // height: hp(50),
    paddingVertical: hp(15),
    borderRadius: hp(50),
    borderWidth: hp(1),
    marginRight: hp(15),
    marginTop: hp(15),
    borderColor: colors.blueColor,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(28, 43, 75, 0.2)",
  },
  labelPlaceholder: {
    height: hp(15),
    width: wp(170),
    borderRadius: 5,
    marginTop: hp(25),
  },
  lowerContainer: {
    width: "90%",
    paddingBottom: hp(15),
    alignSelf: "center",
  },
});
